User.create!(email:"bloodyblue@gmail.com", password:"123456")
Place.create(title:"Beautiful Ghost", address:"Beelitz, Brandenburg", description:"1 double bed", price:800, user_id:1)
Place.create(title:"Stay a night with me", address:"Geethowan", description:"2 single beds", price:1000, user_id:1)
Place.create(title:"Beelitz Heilstätten", address:"Brandenburg", description:"one double bed with a pool", price:1200, user_id:1)
Place.create(title:"Touch me if you can", address:"Beelitz", description:"Two beds with ghost skelton", price:1400, user_id:1)
